export const REFRESH_TOKEN_TTL_DAYS = 30;
export const EMAIL_VERIFICATION_TOKEN_TTL_DAYS = 7;
export const PASSWORD_RESET_CODE_TTL_MINUTES = 10;
export const PASSWORD_RESET_MAX_ATTEMPTS = 3;
export const PASSWORD_RESET_SESSION_TTL_MINUTES = 10;